### ISSUE TITLE
Bible verse links broken after latest update

### ISSUE THREAD

**Issue by daniel-odrinski** [Adventech/sabbath-school-android#1097]
Hi Adventech (@TinasheMzondiwa),

The latest update (v4.51.0) broke Bible verse links for me.

I have reproduced this issue on two separate Android devices (where I had upgraded the app on the first device and installed the app freshly on the second device). Whenever you go to tap on a verse link in any lessons, it just does nothing. It is tappable, though.

The two Android devices are running Android 14 and Android 13, respectively.

Please verify the latest release and roll-back the changes if necessary.
Thanks.
Daniel

**Comment by daniel-odrinski** [comment]
Android 14 screen recording:
https://github.com/Adventech/sabbath-school-android/assets/22768251/4b4786f2-b107-458d-97ae-fac54d2c9e65

No matter which lesson I try, the verse links do not work. Clearing the lessons does not help.

**Comment by daniel-odrinski** [comment]
Android 13 screen recording:

https://github.com/Adventech/sabbath-school-android/assets/22768251/5666bc92-0d22-4db2-80cc-921b5fc45c9a

**Comment by TinasheMzondiwa** [comment]
Thanks for the report @DanWiseProgramming 

Do you mind sharing the exact version number you have installed.

I have the latest production version `4.51.0 (11347)` and cannot reproduce that issue.

https://github.com/Adventech/sabbath-school-android/assets/5994683/3e5c930a-960c-4658-8c2c-f4078f145faf

**Comment by daniel-odrinski** [comment]
4.51.0 (22308) installed from Google Play Store.

Android 14 (auto-updated a few days ago):

![Screenshot_20240615-071924](https://github.com/Adventech/sabbath-school-android/assets/22768251/6afa1ee8-d891-4731-b61a-8d4693a1d721)

Weirdly enough, Google Play store states that the latest version build is the one you pointed out 🤔 despite that, it installed (this morning) build 22308 on the Android 13 device anyway...

![Screenshot_20240615-073010](https://github.com/Adventech/sabbath-school-android/assets/22768251/9fb739dc-6d67-46da-a10b-dac2d023bcbe)

Android 13 (installed this morning from Google Play to test on second device):

![Screenshot_20240615_062544_Sabbath School](https://github.com/Adventech/sabbath-school-android/assets/22768251/37fe0d73-d890-4db7-b8e8-0d157f68f705)

![Screenshot_20240615_062957_Google Play Store](https://github.com/Adventech/sabbath-school-android/assets/22768251/1af3324c-1942-4f9f-8f9e-7a41ce907644)

I am not in the Google Play Beta Program for this app.

**Comment by TinasheMzondiwa** [comment]
I could reproduce the issue and the [fix](https://github.com/Adventech/sabbath-school-android/commit/20638df843a54df7886083016b3ffa47ca3d03a7) will be in a new version `4.52.0 (22332)`
This issue was only present in the public Beta build and not in production. You must've enrolled in the public Beta.

Thanks for the report again.
