### ISSUE TITLE
Scripture links don't respond when touched 

### ISSUE THREAD

**Issue by rburrowes** [Adventech/sabbath-school-android#1098]
Recently I have found that the links the adult lessons to the Bible scriptures is not responding to touchscreen inputs.
The verses quoted are not displayed.

I'm using a Google Pixel 6a device.
My default Bible version in the app is KJV.
I first noticed this behaviour late last week (Thursday or Friday)

**Comment by TinasheMzondiwa** [comment]
Thanks for the report.
This issue has been fixed and we're just waiting on Google to review the update with the fix. Also reported in #1097
