### ISSUE TITLE
Bible Verses Reading Fragment Doesn't Preserve Scroll State on Screen Rotation or Process Death

### ISSUE THREAD

**Issue by pherasymchuk** [Adventech/sabbath-school-android#1103]
**Description:**
When reading Bible verses in the Sabbath School app, the scroll position is not preserved when the screen is rotated or when the app process is killed and restarted. This leads to a poor user experience as users have to manually find their last reading position every time these events occur.

**Steps to Reproduce:**
1. Scroll down to a specific verse.
2. Rotate the screen or kill the app process and restart it.
3. Observe that the scroll position is reset to the top of the fragment.

**Expected Behavior:**
The app should save the current scroll position and restore it when the screen is rotated or the app process is restarted, so that users can continue reading from where they left off.

**Actual Behavior:**
The scroll position is reset to the top of the fragment, requiring users to manually scroll to their last reading position.

**Environment:**
- App Version: 4.55.0 (22341)
- Device: Xiaomi Mi 9T Pro
- OS: Android 14
![Screenshot_20240728-074839_Sabbath School](https://github.com/user-attachments/assets/b51892c8-32db-4083-89cd-4292b7a3381f)

**Comment by VitalikL** [comment]
@pherasymchuk Thanks for submitting. 

I think the rotation and app switch makes sense (but not killing the process). @TinasheMzondiwa one way to reproduce is to open Bible verse that has enough content to scroll and then swipe to go home and return to the app -> the scroll position is lost.

**Comment by TinasheMzondiwa** [comment]
> open Bible verse that has enough content to scroll and then swipe to go home and return to the app -> the scroll position is lost

I can reproduce this and will investigate a fix.

Rotation is locked to device portrait though, Does this screen rotate for you?

**Comment by VitalikL** [comment]
@TinasheMzondiwa Rotation applies to tablets only.
