### ISSUE TITLE
Fix bottom sheet navigation bar color

### ISSUE THREAD

**Issue by TinasheMzondiwa** [Adventech/sabbath-school-android#160]
Fix bottom sheets navigation bar color on < 29 devices.
Issue: white navigation bar icons on white navigation bar 

![image](https://user-images.githubusercontent.com/5994683/107712377-506b4180-6c97-11eb-9ecd-835b76906ba8.jpeg)

**Comment by merlin-zaraza** [comment]
The same in lesson types
