### ISSUE TITLE
Introductory text to the quarter is being cut off 

### ISSUE THREAD

**Issue by agmo-byte** [Adventech/sabbath-school-android#186]
If you look at this quarter's (the covenant 2nd quarter 2021) introduction, next to the cover image, the text is cut off with ellipsis. So it makes no sense and there is no way to read the rest of it. Might be nice to have a dedicated page for it as the paper lesson does.
![Screenshot_20210413-124103](https://user-images.githubusercontent.com/80777847/114590690-15659a00-9c57-11eb-9345-76af0cf2d719.png)

**Comment by TinasheMzondiwa** [comment]
Hi @agmo-byte,
This screen is being re-designed  at the moment and work will begin soon to address this issue.

**Comment by Caligal** [comment]
Thank you so much for the SS app. This issue is still ongoing with the new quarter, cuts off the introduction. I have no skills so unfortunately, I'm unable to help, but will appreciate your efforts!

**Comment by Caligal** [comment]
You closed this, but the problem remains unfixed in the new quarterly.

**Comment by VitalikL** [comment]
@Caligal Already implemented in the beta version, closing as release is going to happen soon
