### ISSUE TITLE
No EGW Quotes?

### ISSUE THREAD

**Issue by CZelie** [Adventech/sabbath-school-android#239]
Hi all,

Can you please give feedback in regards to why no EGW quotes?

Additional Reading: Selected Quotes from Ellen G. White
We apologize that the daily quotes by Ellen White are temporarily unavailable. We are working toward providing supplemental quotations again in the very near future!

Thank you in advance

Kind regards,

Elder Clayton

**Comment by VitalikL** [comment]
Hello @CZelie ,

Selected quotes from EGW are temporarily unavailable. Rest assured, they are coming back. At this time we are hoping to get them back before end of this quarter.
