### ISSUE TITLE
Dates on Sabbath school lesson on a different language

### ISSUE THREAD

**Issue by tonigancea** [Adventech/sabbath-school-android#255]
![Screenshot_2021-08-28-16-50-50-58_0cdae84d656205ae7f33f8403f990b25](https://user-images.githubusercontent.com/14114723/131220242-0c826033-0d57-413a-ae3a-52f68273559b.jpg)
![Screenshot_2021-08-28-16-51-46-14_0cdae84d656205ae7f33f8403f990b25](https://user-images.githubusercontent.com/14114723/131220243-bf5f7992-891a-47c7-aa0d-dba519167a32.jpg)

Hello! I think there is a issue with dates on the Romanian version of sabbath school. For example check Sabbath Rest lesson from screenshots. Thank you!

**Comment by VitalikL** [comment]
@tonigancea This issue should be fixed now. Thank you!

**Comment by tonigancea** [comment]
Thank you!
