### ISSUE TITLE
Dark mode not working for new quarterly pages.

### ISSUE THREAD

**Issue by MacariusD** [Adventech/sabbath-school-android#270]
I'm on Oxygen OS 11.1.1.1/Android 11

**Comment by TinasheMzondiwa** [comment]
@MacariusD do you have any screenshots?

**Comment by MacariusD** [comment]
Attached here...
[Screenshot_20211008-094313.jpg](https://user-images.githubusercontent.com/49547750/136576944-135caa26-a6b8-406d-84b6-f5522c3cb81c.jpg)
[Screenshot_20211008-094306.jpg](https://user-images.githubusercontent.com/49547750/136576923-3d2a8b69-5503-4d07-ba68-ba8c6a3f36e1.jpg)

**Comment by VitalikL** [comment]
Looks like its the Reading options which at the moment are not tied to the
dark mode on the device. You might need to manually select Dark. we will
work on the "Device" appearance so it will change depending on the device
setting

**Comment by MacariusD** [comment]
Correct. The "Reading Options" icon appeared to me as only font options so never checked that, I was only manually adjusting it from the main settings option as I assumed it would be more global for the app. Setting it to "Device settings" (I assume you are referring to the global dark mode of later android OSs) makes sense but not everyone has that set, as some people adjust based on how much white is there within some apps. It should still be possible to not have dark mode set from device global but be able to set it for the sabbath school app.

**Comment by MacariusD** [comment]
Dark mode from reading options works and did set it for me. Thanks for the swift response. Love the app and will continue to use it moving forward.
