### ISSUE TITLE
Esonia Sabbath School Adult Lesson Hebrews Bible verser are empty

### ISSUE THREAD

**Issue by Pmarva** [Adventech/sabbath-school-android#284]
Hello i have problem, in Estonia Sabbath School Adult Lesson Hebrews* Bible verser are empty.

example Saturday 15 January 2022 Hb 1(short version in Estonia, long name is _Kiri Heebrealastele_) (Hebrews 1 in English) showing empty verse. And a lot of ohers Hebrews also showing empy. Pible version in Estonia is EEP, 

Photo from app when verse is empty
https://photos.app.goo.gl/SLHXsq1UUZFXoj477

App version is 4.7.2 android 11

**Comment by VitalikL** [comment]
Thank you @Pmarva . We will fix the Estonian Bible

**Comment by VitalikL** [comment]
Fixed now
