### ISSUE TITLE
Backgroundpicture of the quarterly lesson is not shown when Animator duration scale is off

### ISSUE THREAD

**Issue by GitHub-for-Tobias** [Adventech/sabbath-school-android#304]
Hi,
opening the lesson from the main list, the background picture of the quarterly lesson (not the background picture of the week lesson) is not shown every time when the Animator duration scale is off (developer options).

It is reproducible.
Set animator duration scale to off.
1. open the quarterly lesson, background picture is not shown
2. use the back button
3. redo step 1+2 until the picture is shown

If the scale is set to 0.5x it is shown every time. Default is 1x.

Tested on (same result)
SM-G965F LineageOS 18.1 (Android 11)
SM-G960F LineageOS 18.1 (Android 11)
SM-F900F LineageOS 16.0 (Android 9)

Thanks,
Tobias

PS:
https://trendblog.net/android-device-animations/

**Comment by VitalikL** [comment]
@TinasheMzondiwa
