### ISSUE TITLE
Sabbath School data missing from formatted layout

### ISSUE THREAD

**Issue by ezra-en** [Adventech/sabbath-school-android#317]
Expected data:
![Screenshot_20220516-102305_Sabbath School.png](https://user-images.githubusercontent.com/7076802/168509388-ffcbb267-115a-4d53-a61b-07ecd316bc88.png)

Actual data:
![Screenshot_20220516-102019_Sabbath School.jpg](https://user-images.githubusercontent.com/7076802/168509438-ac79b730-303d-4b1f-b8c1-f3fb062e599d.jpg)

A large portion of the lesson is missing. May be a problem with this specific lesson, or with the exporter in general.

**Comment by TinasheMzondiwa** [comment]
Thank you @EzraEn1 
Please open this issue in the [Sabbath-School-Lessons](https://github.com/Adventech/sabbath-school-lessons) project instead.
