### ISSUE TITLE
Intro and Walkthtough (tutorial)

### ISSUE THREAD

**Issue by VitalikL** [Adventech/sabbath-school-android#34]
- [ ] Intro with 3 (?) slides about features
- [x] Language filter icon prompt
- [ ] Reading mode icon prompt

**Comment by imasaru** [comment]
@VitalikL A slide should also be added to introduce the swipe-navigation feature, no?

- [ ] Include slide about swipe navigation

[Update Dec 7] Hmm, even now I'm still seeing reviews about that... Can we see if editing the app description helps until the introduction is finished?
