### ISSUE TITLE
In the german Bibleversion Luth1912 the gospel Luke is not rendered 

### ISSUE THREAD

**Issue by cdbieling** [Adventech/sabbath-school-android#461]
If you read the Sabbath-school lessons in german language, selecting the "Luth 1912" bibelversion, the Gospel luke is rendered blank. 

How to get into this problem: 
1) Open german bible-lesson 
2) Click on a linked bible-Vers, linked to the Gospel Luke
Result Screen is empty / white.

How to avoid the problem: 
Changing to LUTH1545-version avoids the problem.

**Comment by TinasheMzondiwa** [comment]
Thanks for the report @dbieling.
Could you please open this issue in https://github.com/Adventech/bible-tools instead
