### ISSUE TITLE
No some symbols in ukrainian texts with Sony devices

### ISSUE THREAD

**Issue by merlin-zaraza** [Adventech/sabbath-school-android#50]
## There are missing symbols on Sony devices with Android 4.3 (Tested on Sony Xperia SP and Sony Xperia V). Should be fonts related issue in WebView, but I'm not sure. Look to screenshot attached:

![2016-11-10 12-13-00 - sony xperia sp - android 4 3 0](https://cloud.githubusercontent.com/assets/5223485/20176388/3d4bb5c8-a750-11e6-8cbf-0be7ab1df72d.png)

**Comment by VitalikL** [comment]
@merlin-zaraza Thanks! There are some changes been committed recently in regards to fonts and Cyrillic compatibility. Are you ok if I add you to fabric beta so you can test?

**Comment by merlin-zaraza** [comment]
I'm already in beta :)
Also I can build from sources.

**Comment by VitalikL** [comment]
@merlin-zaraza You are probably in Play Store beta which is kinda slow in rollouts. I can add you to fabric beta which is very fast.

**Comment by merlin-zaraza** [comment]
Ok, please add me.

**Comment by VitalikL** [comment]
@merlin-zaraza What's your email? (you can send me email to vitaliy@adventech.io)

**Comment by merlin-zaraza** [comment]
"Lato" font still has issues. The rest seems fixed.
Will test on one more device when being at home.

**Comment by VitalikL** [comment]
@merlin-zaraza Is that only "Sony Xperia Z" or Nexus 6p also have this issue?

**Comment by merlin-zaraza** [comment]
Only "Sony Xperia Z"

**Comment by merlin-zaraza** [comment]
BTW, you can use Genymotion https://github.com/codepath/android_guides/wiki/Genymotion-2.0-Emulators-with-Google-Play-support

**Comment by VitalikL** [comment]
@merlin-zaraza Were you able to reproduce it in Genymotion?

**Comment by merlin-zaraza** [comment]
I have Sony Xperia V at home and firstly reproduced in this device yesterday.
Today I left my Xperia V at home, so I've created Sony Xperia Z with Android 4.3 in Genymotion and able to reproduce it. It seems common issue for Sony devices.

**Comment by VitalikL** [comment]
Ah i see. Thanks

**Comment by VitalikL** [comment]
@merlin-zaraza Issued new beta in fabric with fixes

**Comment by merlin-zaraza** [comment]
It fixed now. Thanks.
