### ISSUE TITLE
No offline access to lessons

### ISSUE THREAD

**Issue by merlin-zaraza** [Adventech/sabbath-school-android#51]
**Lesson load never ending in offline.
Lesson day is blank or empty in offline.**
![screenshot_20161111-194018](https://cloud.githubusercontent.com/assets/5223485/20228895/21af7bc6-a85c-11e6-8c22-d1c602d2e4e7.png)
![screenshot_20161111-194105](https://cloud.githubusercontent.com/assets/5223485/20228896/21b0981c-a85c-11e6-984a-0284387ff173.png)

**Comment by VitalikL** [comment]
@merlin-zaraza Latest beta includes enhancement on this one. Downloads lesson fully if connection. Shows the retry button if no lesson and no connection.
