### ISSUE TITLE
Ligatures not visible in text

### ISSUE THREAD

**Issue by hso** [Adventech/sabbath-school-android#52]
Typographical Ligatures, like 'fi' are blank. Words like 'confianza' or 'fidelidad' appear as 'con anza' and 'delidad'. This could be mildly annoying or downright confusing in some cases.

![tmp_28604-capture _2016-12-03-01-06-53180696701](https://cloud.githubusercontent.com/assets/68519/20856710/e3eb99ba-b8f4-11e6-9716-b7ec1de4915e.png)

**Comment by VitalikL** [comment]
@hso Can you take a look at [this repo](https://github.com/Adventech/sabbath-school-lessons/tree/master/src/es/2016-04) and see if it's the copy-pasting issue or the Android rendering issue

**Comment by hso** [comment]
@VitalikL it's definitely a copy-pasting issue. The ligatures are not in the text.

**Comment by VitalikL** [comment]
@hso Can you check if latest lesson (2016-04/11) has this issue in Spanish

**Comment by hso** [comment]
@VitalikL It seems alright! Thank you! :) What was it?
