### ISSUE TITLE
Lesson title it is hard to read

### ISSUE THREAD

**Issue by gabrielbrieva** [Adventech/sabbath-school-android#53]
The toolbar background image causes some problems reading the lesson title. For this case a gradient between title and background is recommended. You can use Palette to define gradient colors.

**Comment by VitalikL** [comment]
@tuxan Can you specify which lesson that was (language, quarterly, week and day). Thanks

**Comment by gabrielbrieva** [comment]
@VitalikL you already removed the background image from some toolbars (you are using a solid color) so now the day tittle is readable.
This was the problem [screenshots](https://drive.google.com/drive/folders/0B5YfPgP322leTjJRcWJ1Z2xCbmM?usp=sharing)

**Comment by VitalikL** [comment]
We have made some changes to make text more visible @tuxan

**Comment by gabrielbrieva** [comment]
I think this issue is not solved. You can use a gradient over the toolbar image like this https://raw.githubusercontent.com/tuxan/xyzreader/master/screenshots/device-2016-03-22-004050.png

**Comment by jwgarrett** [comment]
I agree as I am having the same issue.

**Comment by merlin-zaraza** [comment]
@VitalikL We can add shadow to the title and subtitle so text will be more visible. I can create pull request for that
