### ISSUE TITLE
Localize date mask in lessons

### ISSUE THREAD

**Issue by imasaru** [Adventech/sabbath-school-android#63]
The default date format looks a bit odd and is sometimes harder to read when carried over to Japanese.

![Original](https://farm5.staticflickr.com/4300/35622797870_0951b67c06_n.jpg)

I suggest implementing something like this: 

![Suggestion](https://farm5.staticflickr.com/4309/35841278132_9361c636a7_n.jpg)

Hopefully this will be possible to implement without messing up the date formatting for the other languages.

**Comment by VitalikL** [comment]
@imasaru What is the date formatting string would be for this?

**Comment by imasaru** [comment]
Something like `yy.MM.dd`, at least. If you want to preserve the style that you used with English, you can omit the year like I did in the second photo above. 

In that photo, I tried to preserve the day, month, and year as much as possible, creating: 
`MM月.dd日 (EEE)`

**Comment by hebertialmeida** [comment]
We have to localize the date mask, so it will be good for any language.
