### ISSUE TITLE
Supplementary EGW Notes - incorrect page numbers 

### ISSUE THREAD

**Issue by rburrowes** [Adventech/sabbath-school-android#655]
Actual:
Page numbers referenced are not always accurate.
In the example screenshot the page number quoted is **347**
![Screenshot_20230503-060532](https://user-images.githubusercontent.com/26167747/235831830-689b4840-c525-4a83-970f-dcf008876c2a.png)
When reading the same quote from the [EGW Writings](https://play.google.com/store/apps/details?id=com.whiteestate.egwwritings) app 
![Screenshot_20230503-060513](https://user-images.githubusercontent.com/26167747/235834293-8f5bfbd5-dfeb-4545-a37a-b4a1a1dc2c3d.png)
 or from https://m.egwwritings.org/en/book/132.1565 the page number is **346.4**

Expected:
The page number to be correctly quoted.

Suggestion:
Would it be possible to link to the EGW Writings app the exact quote or to link the quotes' webpage? The user can gain a wider understanding of the context of the quote.

I regularly study more regarding the supplementary EGW Notes and noted inaccurate page numbers on more than one occasion.

This suggestion would equally apply to Bible quotes when a user may wish to search more around the quoted scripture.

God bless!

**Comment by TinasheMzondiwa** [comment]
Thanks for the report @rburrowes, could you please open this issue in the [sabbath-school-lessons](https://github.com/Adventech/sabbath-school-lessons) project instead.
This is where the content itself is managed.
