### ISSUE TITLE
Problem with updating previously downloaded lessons

### ISSUE THREAD

**Issue by tkacikr** [Adventech/sabbath-school-android#691]
Currently I have a problem that the lessons downloaded early are not updated (in the new quarter) in Android.
For example: I first opened lesson 10 before more than two weeks. Audio and Inside story was updated/commited/pullRequested both in git before several days (Audio was added, Inside story was updated). Now I open lesson 10 again - Audio was updated but Inside story not.

I have to delete the data from the application (or uninstall and reinstall the application) and then it will be ok.

Screenshot:

![screenshot_2023-05-27-09-40-31-739_com.cryart.sabbathschool.jpg](https://github.com/Adventech/sabbath-school-android/assets/50102350/fe3bfb34-bfc2-4eb9-aecf-5d9ee40d8f5b)

**Comment by tkacikr** [comment]
When will this patch be released, please? (In which version of the app?)

**Comment by TinasheMzondiwa** [comment]
@tkacikr Can you still reproduce this issue in version `4.30.0`?

**Comment by tkacikr** [comment]
@TinasheMzondiwa The problem.still persists. I would have liked at least a some refresh button or refresh gesture.

**Comment by TinasheMzondiwa** [comment]
Working on this next
