### ISSUE TITLE
Using Git Flow

### ISSUE THREAD

**Issue by vovs03** [Adventech/sabbath-school-android#80]
# Git Flow

Why accepting in **master branch** untested commits?
Maybe create another branches for test features?

## Real fact

[Build Failure](https://travis-ci.org/Adventech/sabbath-school-android/jobs/329285336#L2293)

**Comment by VitalikL** [comment]
@KeyJoo Good idea. We can have stage / beta branch for untested branches and have master to be merged upon success only. The above failure is actually due to Travis and updated deps for Android SDK.

**Comment by imasaru** [comment]
@VitalikL @Vlad-Pavlychief Maybe we can add `stage` branch now since @osinvladislav is going to work on this?

**Comment by vovs03** [comment]
Wow, it's listen perfectly

**Comment by imasaru** [comment]
@vovs03 Also, I think this is why the build failed:

Lines [2279](https://travis-ci.org/Adventech/sabbath-school-android/jobs/329285336#L2279)~[2286](https://travis-ci.org/Adventech/sabbath-school-android/jobs/329285336#L2286)

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 27].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by VitalikL** [comment]
Closing since we now have the test and develop branch
