### ISSUE TITLE
Improve offline functionality

### ISSUE THREAD

**Issue by imasaru** [Adventech/sabbath-school-android#82]
A number of users have been writing reviews saying that they would like a feature for reading lessons offline. We've had this feature for almost half a year now...

Thus I suggest that we add this as one of the features in the Play Store description.

**Comment by VitalikL** [comment]
Technically, it is possible to use it offline, but we need to add more functionality regarding offline usage. For instance, app should show which lessons were downloaded and which weren't and etc. However, I agree, we can improve it by also mentioning the offline functionality in the description

**Comment by imasaru** [comment]
@vitalikL And even a "download all," e.g. for whole quarter, like one user said.

I think Stefan's app has sophisticated offline functionality like this

**Comment by imasaru** [comment]
@VitalikL Change name to "Improve offline functionality"?

**Comment by VitalikL** [comment]
👍

**Comment by imasaru** [comment]
@VitalikL Done 😛

**Comment by Afolayan** [comment]
Hello. Is this ticket in progress already? Any hand needed? I'm available.

**Comment by imasaru** [comment]
@Afolayan I believe this ticket isn't in progress yet... Ask @VitalikL
