### ISSUE TITLE
Some lessons crash on start when opened for the first time

### ISSUE THREAD

**Issue by synrg** [Adventech/sabbath-school-android#83]
On some devices, some lessons consistently crash the app when opened for the first time (for me, that's most often in portrait orientation). Sometimes just reopening the same lesson later succeeds, and sometimes it doesn't. Rotating the device from portrait to landscape orientation and reopening the lesson again often works around the issue for the stubborn cases.  

Reproducible on Zenfone 3 Laser with current stock firmware and 24 March - 30 March 2018 lesson.

The issue is not new. It has existed for several months of releases of the app, but I only just today discovered your issue tracker. Also, it is not specific to one device. I also experience it on my Nexus 7 Wi-Fi 2013 tablet running LineageOS 14.1 (Android 7.1.2), for instance.

**Comment by imasaru** [comment]
@synrg Yep, this one's been around for a while, and I think just about everyone is aware of it... It's just so normal that I've forgotten to make an issue on it :sweat_smile:

I had that issue just this morning, actually.

**Comment by VitalikL** [comment]
Thanks @synrg. This is strange and I will investigate. I personally did not experience this issue, but that could certainly be due to the different manufacturer.

**Comment by Afolayan** [comment]
I do notice this on my device too. I use an Infinix X559C, Android 7. It happens the first time the lesson is loaded.

**Comment by imasaru** [comment]
Hello, everyone, are you still experiencing crashes? @VitalikL pushed a fix for this a couple of months ago. If so, we can close this issue, no? :ok_hand:

**Comment by VitalikL** [comment]
@imasaru @synrg @Afolayan Yes, this has been fixed with the latest release :)
