### ISSUE TITLE
Sorting textbooks to see latest on the top

### ISSUE THREAD

**Issue by merlin-zaraza** [Adventech/sabbath-school-android#84]
### Now it's looks unordered:
![photo_2018-04-03_11-29-28](https://user-images.githubusercontent.com/5223485/38238516-bca25048-3732-11e8-9402-6050f0b14f12.jpg)

### Sabbath School version is 3.2.940 (28)

**Comment by VitalikL** [comment]
That is only happening in Stage (Beta) environment. I will fix it in about
few hours
