### ISSUE TITLE
Dark theme: after clicked link - white screen 1 second!

### ISSUE THREAD

**Issue by vovs03** [Adventech/sabbath-school-android#87]
# :bulb: Hard light at night! 

- When user click by link before it will be open, user see clear white screen (1 second), after that he can read Bible text.
- It is a :bug: (bug)

> Андрей Бедратый  
8 июня 2018 г.  
Лучшая программа. В задумке недостатков не нашёл. Приятно удивил перевод Кулакова. Супер! Есть пару пожеланий. Я читаю в темном фоне, но при нажатии на библейскую ссылку на долю секунды включается белый фон. Успевает ослепить. На iОсь такого нет. И ещё. Нельзя ли сделать, чтобы при открытии текста можно было бы, по желанию открыть всю голову для контекста. А то приходится открыть другое приложение. И тогда, для меня программа будет идеальной.  
source: [Google play](https://play.google.com/store/apps/details?id=com.cryart.sabbathschool)

**Comment by Adham32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dark theme: after clicked link - white screen 1 second! #87](https://trello.com/c/dKkpq4Bg/3-dark-theme-after-clicked-link-white-screen-1-second-87)
