### ISSUE TITLE
Highlighting has different outcomes between WebApp and Android App

### ISSUE THREAD

**Issue by meVadimFord** [Adventech/sabbath-school-android#877]
There appears to be an error in how text highlighted on the WebApp gets displayed in the Android App. It seems to be off by 11 characters between the two platforms. I've originally highlighted the sentence "Anyone can say that he or she loves God; doing it, however, requires conscious effort." on the WebApp. 
![WebApp Desktop](https://github.com/Adventech/sabbath-school-android/assets/96389308/d874f0c5-b727-406e-9cfb-be34a6786fd5)
When I view it on the Android App it appeared like this:
![Adroid App Samsung A22](https://github.com/Adventech/sabbath-school-android/assets/96389308/6a3725ce-e289-4582-b57c-0dda88c804ea)

**Comment by VitalikL** [comment]
Hi @meVadimFord , thanks for reporting the issue, could you please verify if by web-app you mean `sabbath-school.adventech.io` version, since there are multiple other websites that pull from the API.

**Comment by meVadimFord** [comment]
That is correct @VitalikL .

**Comment by VitalikL** [comment]
@meVadimFord The highlights are being reworked as part of the next major milestone to move away from WebView.
