### ISSUE TITLE
The ability to read the entire chapter

### ISSUE THREAD

**Issue by vovs03** [Adventech/sabbath-school-android#88]
# :scroll:  The ability to read the entire chapter

When user click by link to Biblical text, he can read currently Bible verse only. If he want to read full chapter, he need use third-party application Bible. `It's not true`

- [ ] Add the ability to read the entire chapter (Full context). **Feature**

**Comment by Adham32** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The ability to read the entire chapter #88](https://trello.com/c/aRw41MWM/4-the-ability-to-read-the-entire-chapter-88)
