### ISSUE TITLE
Cannot Open today's lesson nor lessons for this week 

### ISSUE THREAD

**Issue by rburrowes** [Adventech/sabbath-school-android#94]
This was not happening the previous days this week.

1. Launch the app
2. Touch the Read button
3. App flickers and settles down on the current quarterly. 
4. Touch the selection for this week's lesson. 
5. App flickers and settles down on the current quarterly.
6. Touch the selection for any other week's lesson.
7. The Sabbath lesson for the selected week is opened 

Steps 3 and 5 are the issue.

**Comment by imasaru** [comment]
Good morning @rburrowes! What are your device specifications?

**Comment by rburrowes** [comment]
Good morning,

My device is an Honor 9X. I hope that the attached screenshot is sufficient
for the specifications you require.

God bless,

**Comment by VitalikL** [comment]
@rburrowes @imasaru Hotfix is on the way!

**Comment by Pmarva** [comment]
I have same problem.

**Comment by VitalikL** [comment]
@Pmarva @rburrowes Does it still happening? Can you try doing screen recording of the issue?

**Comment by rburrowes** [comment]
I am not experiencing the same issue with this week's lesson. I cannot re-create the issue any more.
But did see it on 2 separate occasions when I raised this bug. Each time after some days it was OK.

**Comment by Pmarva** [comment]
I had time to record the bug.

https://drive.google.com/file/d/1GcnhFiHgIRZZanr_3xbrJFV8CQ_6wR7b/view?usp=sharing

**Comment by TinasheMzondiwa** [comment]
@Pmarva would you mind updating to the latest Beta **Release:	3.2.1343**
And see if you can still reproduce this issue.

**Comment by Pmarva** [comment]
@TinasheMzondiwa  I tried the 3.2.811 version but under menu it still showed version 3.0
Can you send me the apk file?

I think the problem is in the lesson files because if i changed language to the Germany, English, Finnish then there were no problems.

I am using Estonian.
